prometheus:
  prometheusSpec:
    ignoreNamespaceSelectors: true
    scrapeNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - default
    podMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - default
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - default
    ruleNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - default
    # Target-level filtering (prevent scraping targets in default namespace)
    relabelConfigs:
      - sourceLabels: [__meta_kubernetes_namespace]
        regex: default
        action: drop
    # Metric-level filtering (prevent storing metrics from default namespace)
    metricRelabelConfigs:
      - sourceLabels: [__meta_kubernetes_namespace]
        regex: default
        action: drop
      - sourceLabels: [namespace]
        regex: default
        action: drop
      - sourceLabels: [pod, namespace]
        regex: .+;default
        action: drop
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

kube-state-metrics:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"